Data Structures, Functions, Numpy & Pandas

Section A: Data Structures & Control Structures


List Operations

In [1]:
# Create a list of 5 integers
numbers = [40, 10, 30, 20, 50]
print("Initial list:", numbers)

# append: adds 60 to the end of the list
numbers.append(60)
print("After append(60):", numbers)

# extend: adds [70, 80] to the end of the list
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# insert: inserts 25 at index 2
numbers.insert(2, 25)
print("After insert(2, 25):", numbers)

# remove: removes the first occurrence of 30
numbers.remove(30)
print("After remove(30):", numbers)

# pop: removes and returns the last element
popped_value = numbers.pop()
print("After pop():", numbers, "(Popped value was:", popped_value, ")")

# index: finds the index position of the value 20
position = numbers.index(20)
print("Index of 20:", position)

# count: counts how many times 50 appears in the list
occurrences = numbers.count(50)
print("Count of 50:", occurrences)

# sort: sorts the list in ascending order
numbers.sort()
print("After sort():", numbers)

# reverse: reverses the list order
numbers.reverse()
print("After reverse():", numbers)

# clear: removes all elements from the list
numbers.clear()
print("After clear():", numbers)

Initial list: [40, 10, 30, 20, 50]
After append(60): [40, 10, 30, 20, 50, 60]
After extend([70, 80]): [40, 10, 30, 20, 50, 60, 70, 80]
After insert(2, 25): [40, 10, 25, 30, 20, 50, 60, 70, 80]
After remove(30): [40, 10, 25, 20, 50, 60, 70, 80]
After pop(): [40, 10, 25, 20, 50, 60, 70] (Popped value was: 80 )
Index of 20: 3
Count of 50: 1
After sort(): [10, 20, 25, 40, 50, 60, 70]
After reverse(): [70, 60, 50, 40, 25, 20, 10]
After clear(): []


Tuple Mutability

In [2]:
# Create a tuple of 3 student names
students = ("Amit", "Pooja", "Raj")
print("Initial tuple:", students)

# Try changing the second name ('Pooja' to 'Neha')
try:
    students[1] = "Neha"
except TypeError as error:
    print("\n--- Error Occurred ---")
    print(error)
    print("\n--- Explanation ---")
    print("Tuples in Python are IMMUTABLE. Once a tuple is created,")
    print("its elements cannot be changed, added, or removed.")

Initial tuple: ('Amit', 'Pooja', 'Raj')

--- Error Occurred ---
'tuple' object does not support item assignment

--- Explanation ---
Tuples in Python are IMMUTABLE. Once a tuple is created,
its elements cannot be changed, added, or removed.


Set with Duplicates

In [3]:
# Create a set with duplicate values
my_set = {10, 20, 10, 30, 20, 40, 50, 40}

# Print the set
print("Set output:", my_set)

# Explanation
print("\n--- Explanation ---")
print("A set in Python automatically filters out all duplicate values")
print("and only stores unique elements. Also, sets are unordered,")
print("so the elements may print in a different order than written.")

Set output: {50, 20, 40, 10, 30}

--- Explanation ---
A set in Python automatically filters out all duplicate values
and only stores unique elements. Also, sets are unordered,
so the elements may print in a different order than written.


Dictionary Operations

In [4]:
# Create a dictionary
person = {
    'name': 'Rahul',
    'age': 20,
    'city': 'Mumbai'
}
print("Initial dictionary:", person)

# 1. Update the age
person['age'] = 21

# 2. Add a new key 'email'
person['email'] = 'rahul@example.com'

# Print the final dictionary
print("Final dictionary:", person)

Initial dictionary: {'name': 'Rahul', 'age': 20, 'city': 'Mumbai'}
Final dictionary: {'name': 'Rahul', 'age': 21, 'city': 'Mumbai', 'email': 'rahul@example.com'}


Voting Eligibility Script

In [5]:
# Set age variable
age = 19

# Check if eligible (age must be 18 or above)
if age >= 18:
    print("Eligible to vote.")
else:
    print("Not eligible to vote.")

Eligible to vote.


Grade Evaluation Script

# Set marks variable
marks = 82

# Evaluate grade
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print("Grade:", grade)

Nested Conditions

In [7]:
# Set number variable
number = 12

if number > 0:
    # Nested check for positive number
    if number % 2 == 0:
        print(number, "is positive and even.")
    else:
        print(number, "is positive but odd.")
elif number == 0:
    print("The number is zero.")
else:
    print(number, "is negative.")

12 is positive and even.


Section B: Numpy

Numpy Array Creation

In [8]:
import numpy as np

# A scalar using np.array(5)
scalar = np.array(5)
print("Scalar:")
print(scalar)

# A 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array_1d)

# A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60]])
print("\n2D Array (2x3):")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array (2x3):
[[10 20 30]
 [40 50 60]]


Random Array Generation

In [9]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[42 89  0 29]
 [49 12 65 12]
 [26 71 83 40]
 [23 88 84 93]]


Array to Pandas DataFrame

In [11]:
import numpy as np
import pandas as pd

# Create a 2D numpy array of shape 3x3
array_3x3 = np.array([[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]])

# Convert it into a pandas DataFrame and add column names
df = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])

print("Converted DataFrame:")
print(df)

Converted DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas

DataFrame Operations

In [12]:
import numpy as np
import pandas as pd

# 1. Create a DataFrame manually with 10 rows (includes some missing values and a duplicate row to demonstrate cleanup)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack', 'Alice'],
    'Age': [25, 30, 35, 40, 22, 28, 33, 45, 29, 31, 25],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Pune', 'Kolkata', 'Hyderabad', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Mumbai'],
    'Salary': [50000.0, 60000.0, np.nan, 80000.0, 45000.0, np.nan, 70000.0, 95000.0, 55000.0, 65000.0, 50000.0]
}
df = pd.DataFrame(data)
print("--- Original DataFrame (with missing values and a duplicate row) ---")
print(df)

# 2. Use .info()
print("\n--- .info() Output ---")
df.info()

# 3. Use .describe()
print("\n--- .describe() Output ---")
print(df.describe())

# 4. Select 'Name' and 'City' columns
name_and_city = df[['Name', 'City']]
print("\n--- Selected Name and City Columns ---")
print(name_and_city)

# 5. Drop 'City' column
df_no_city = df.drop(columns=['City'])
print("\n--- DataFrame after dropping City column ---")
print(df_no_city)

# 6. Fill missing values in 'Salary' column with the mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("\n--- DataFrame after filling missing Salaries with Mean (₹" + str(round(mean_salary, 2)) + ") ---")
print(df)

# 7. Remove any duplicate rows
df_cleaned = df.drop_duplicates()
print("\n--- Final Cleaned DataFrame (No duplicates) ---")
print(df_cleaned)

--- Original DataFrame (with missing values and a duplicate row) ---
       Name  Age       City   Salary
0     Alice   25     Mumbai  50000.0
1       Bob   30      Delhi  60000.0
2   Charlie   35  Bangalore      NaN
3     David   40    Chennai  80000.0
4       Eva   22       Pune  45000.0
5     Frank   28    Kolkata      NaN
6     Grace   33  Hyderabad  70000.0
7     Henry   45  Ahmedabad  95000.0
8       Ivy   29     Jaipur  55000.0
9      Jack   31    Lucknow  65000.0
10    Alice   25     Mumbai  50000.0

--- .info() Output ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 484.0+ bytes

--- .describe() Output ---
             Age        Salary
count  11.000